# Generated by Django 5.2.9 on 2026-01-14 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EXPENSE', '支出'), ('INCOME', '收入')], default='EXPENSE', max_length=10, verbose_name='類型')),
                ('category', models.CharField(default='餐飲', max_length=50, verbose_name='類別')),
                ('amount', models.IntegerField(verbose_name='金額')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '收支紀錄',
                'verbose_name_plural': '收支紀錄',
            },
        ),
    ]
