# Generated by Django 5.2.9 on 2026-01-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='資產名稱')),
                ('amount', models.IntegerField(verbose_name='目前總金額')),
                ('interest_rate', models.FloatField(default=1.0, verbose_name='預估年報酬率(%)')),
                ('type', models.CharField(choices=[('CASH', '現金/存款'), ('STOCK', '股票/基金'), ('REAL_ESTATE', '房地產'), ('DEBT', '負債/貸款')], default='CASH', max_length=20, verbose_name='資產類型')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2026, verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('total_income', models.IntegerField(verbose_name='本月總收入')),
                ('total_expense', models.IntegerField(verbose_name='本月總支出')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
