# Generated by Django 5.2.9 on 2026-01-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_asset_monthlyfinancial_delete_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='目標名稱')),
                ('cost', models.IntegerField(help_text='如果是持續支出，請填每年金額', verbose_name='預計金額')),
                ('start_year', models.IntegerField(default=2026, verbose_name='開始年份')),
                ('duration_years', models.IntegerField(default=1, help_text='單次支出請填 1', verbose_name='持續年數')),
                ('type', models.CharField(choices=[('ONE_TIME', '單次支出 (如：買房、買車)'), ('RECURRING', '每年持續 (如：旅遊、孝親、醫療)')], default='ONE_TIME', max_length=10, verbose_name='類型')),
            ],
        ),
    ]
