# Generated by Django 5.2.9 on 2026-01-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_lifegoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inflation_rate', models.FloatField(default=2.0, verbose_name='預估通膨率 (%)')),
                ('return_rate', models.FloatField(default=5.0, verbose_name='預估投資報酬率 (%)')),
            ],
        ),
    ]
